### PR TITLE
feat: adding network template /bind and /unbind

### PR DESCRIPTION
**Pull request by crenus**
Setting up support for network config  template bind/unbind as part of the network resource.

**Task references:**
https://github.com/orgs/core-infra-svcs/projects/1/views/1?filterQuery=bind&pane=issue&itemId=13048104
https://github.com/orgs/core-infra-svcs/projects/1/views/1?filterQuery=bind&pane=issue&itemId=13048286

Bind its self is not really a resource but more just attributes to a network. They are only POST calls and have nothing else to them. Their responses are even the same as the network Model. Thus, made the decision to have them incorporated into the network resource.

### CODE REVIEW

**Comment by crenus** [comment]
Yea let me see if I can take a look at the test. Might need some adjustment. I had run different scenarios locally adding, removing, changing templateId etc and it was working

**Comment by crenus** [comment]
I have no run the test but with my config tryring to test out some scenarios, and I think there are some other issues too. If I change the timezone for example, the Update does not trigger and things plan matches the state. I havent recreated your above issue but my guess is it is cause it is somehow storing in the state and then when reading there is a difference in that its like making unknown and empty string or so

**Comment by crenus** [comment]
Question here at this point. since we are making multiple calls within a single request, in case of failures, should we be storing to the state in the middle of execution? Is that a standard approach when requiring multiple calls In a provider?

**Comment by iamdexterpark** [comment]
> Question here at this point. since we are making multiple calls within a single request, in case of failures, should we be storing to the state in the middle of execution? Is that a standard approach when requiring multiple calls In a provider?

Given the complexity of some resources, it's not uncommon to make multiple API calls within a single request to fully create, update, or delete a resource. However, persisting state data in the middle of execution could lead to inconsistencies between the .tfstate file and the actual end state of the infrastructure. 

Any resource employing that strategy should prioritize error handling so we do not leave infrastructure in a partially configured state in the event of an API call failure. 

In practice, I index toward atomic resources. In this case, if it is possible to have a dedicated resource for binding and unbinding networks, that would be my recommendation.

**Comment by crenus** [comment]
Well so this is where i htink applying state mid execution would make sense. That way if you do have a failure and are in a partial state, you at least have committed what happened. So that if you ran another plan / apply, it would pick up just what wasnt, and make those relative changes.

I think this situation with bind and unbind is a tough one, because all it is, is the action of setting a templateId on the actual resource. And if you do it outside of the network resource, well then the state of the network resource changes outside of your actual changes. Bind and unbind are opposite actions and in my mind would actually make it more challenging to have them as atomic. 

 
Im doing some digging right now, and this does seem to be a common problem that has changed over time. The latest I can find, is that we can write to state, and on error, it will use that written state. So I will attempt that here just to cover bases. While it requires more thought in how we manage the state, I think long term, bit more beneficial

**Comment by crenus** [comment]
So just to follow back on this, what i have done is added:
`resp.State.Set(ctx, &data)`
in between the api calls. At the very least it will save the state, and so if an error occurs, it well set the state to tainted. At which the next plan/apply will attempt to fully replace the resource. You optionally can mark the resource as untainted, which should use the same resource but understand there is a state difference and instead just try to make the bind change.

**Review by iamdexterpark — APPROVED** [review]
Thanks again for this contribution! 

I've cherry-picked the changes in this branch into the pre-release-cleanup branch as it has overlapping changes. 

We need a way to leverage our automated integration framework to test these features; however, the config templates resource must still be developed.  

That said, manual binding/unbinding works. 

Great job, cherry-picked/merged.

**Pull request closed without merging**
